In [1]:
from pola_fixed_point_API import *
import string

In [2]:
reader = {}
#down_dim = np.squeeze(read_gray_picture_from_txt("./lstm_input_feature_map/0.txt",(32,128,1)),axis=-1) 
#up_dim = np.expand_dims(down_dim,axis=0)
#reader["floating_answer"] = up_dim
reader["floating_answer"] = read_gray_picture_from_csv("./lstm_input_feature_map/OCR_imput_feature_map_0.csv")
reader["fixed_answer"]    = np.array([0])
TODO_LIST = ["conv","relu","max_pool"]
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#check your API and change your weight to lstm
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  

In [3]:
'''
floating_answer1 , fixed_answer1 , float_node1 , fixed_node1= layer_information(TODO_List=TODO_LIST,
                                                   layer_number="layer1",
                                                   input_feature_map_array=reader,
                                                   conv=("conv",3,1,1),
                                                   max_pool=("max_pool",(2,2),(2,2)),
                                                   relu=("relu",None),
                                                   #relu=("None",None),              
                                                   batch=("batch",0,("weight",64,1,9),("bias")),
                                                   output_channel=64,
                                                   branch_node = None
                                                   )
np.save('floating_answer1', floating_answer1)
np.save('fixed_answer1', fixed_answer1)
'''
floating_answer1 = np.load("OCR_floating_answer/floating_answer1.npy")
fixed_answer1 = np.load("OCR_fixed_answer/fixed_answer1.npy")


In [4]:
reader = {}
reader["floating_answer"] = floating_answer1
reader["fixed_answer"]    = fixed_answer1
TODO_LIST = ["conv","relu","max_pool"]
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#check your API and change your weight to lstm
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  

In [5]:
'''
floating_answer2 , fixed_answer2 , float_node2 , fixed_node2= layer_information(TODO_List=TODO_LIST,
                                                   layer_number="layer2",
                                                   input_feature_map_array=reader,
                                                   conv=("conv",3,1,1),
                                                   max_pool=("max_pool",(2,2),(2,2)),
                                                   relu=("relu",None),
                                                   batch=("batch",1,("weight",128,64,9),("bias")),
                                                   output_channel=128,
                                                   branch_node = None
                                                   )
np.save('floating_answer2', floating_answer2)
np.save('fixed_answer2', fixed_answer2)
'''
floating_answer2 = np.load("OCR_floating_answer/floating_answer2.npy")
fixed_answer2 = np.load("OCR_fixed_answer/fixed_answer2.npy")


In [6]:
reader = {}
reader["floating_answer"] = floating_answer2
reader["fixed_answer"]    = fixed_answer2
TODO_LIST = ["conv","relu"]
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#check your API and change your weight to lstm
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  

In [7]:
'''
floating_answer3 , fixed_answer3 , float_node3 , fixed_node3= layer_information(TODO_List=TODO_LIST,
                                                   layer_number="layer3",
                                                   input_feature_map_array=reader,
                                                   conv=("conv",3,1,1),
                                                    max_pool=("None",(None,None),(None,None)),
                                                   relu=("relu",None),  
                                                   batch=("batch",2,("weight",256,128,9),("bias")),
                                                   output_channel=256,
                                                   branch_node = None
                                                   )
np.save('floating_answer3', floating_answer3)
np.save('fixed_answer3', fixed_answer3)
'''
floating_answer3 = np.load("OCR_floating_answer/floating_answer3.npy")
fixed_answer3 = np.load("OCR_fixed_answer/fixed_answer3.npy")
print(floating_answer3)


[[[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]
  ...
  [0.00000000e+00 1.86229359e+02 2.21549400e+02 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]]

 [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]
  ...
  [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
   0.00000

In [8]:
reader = {}
reader["floating_answer"] = floating_answer3
reader["fixed_answer"]    = fixed_answer3
TODO_LIST = ["conv","relu","max_pool"]
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#check your API and change your weight to lstm
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  

In [9]:
'''
floating_answer4 , fixed_answer4 , float_node4 , fixed_node4= layer_information(TODO_List=TODO_LIST,
                                                   layer_number="layer4",
                                                   input_feature_map_array=reader,
                                                   conv=("conv",3,1,1),
                                                   max_pool=("max_pool",(2,2),(2,2)),
                                                   relu=("relu",None),
                                                   batch=("batch",3,("weight",256,256,9),("bias")),
                                                   output_channel=256,
                                                   branch_node = None
                                                   )
np.save('floating_answer4', floating_answer4)
np.save('fixed_answer4', fixed_answer4)
'''
floating_answer4 = np.load("OCR_floating_answer/floating_answer4.npy")
fixed_answer4 = np.load("OCR_fixed_answer/fixed_answer4.npy")
print(floating_answer4)


[[[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00 8.68034536e+00 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]]

 [[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]]

 [[1.10647054e+01 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
   0.00000000e+00 0.00000000e+00]
  [0.00000000e+00 2.58400415e+02 0.00000000e+00 ... 4.49419588e-01
   6.60433116e-01 0.

In [10]:
reader = {}
reader["floating_answer"] = floating_answer4
reader["fixed_answer"]    = fixed_answer4
TODO_LIST = ["conv","relu","batch"]
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#check your API and change your weight to lstm
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  

In [11]:
'''
floating_answer5 , fixed_answer5 , float_node5 , fixed_node5= layer_information(TODO_List=TODO_LIST,
                                                   layer_number="layer5",
                                                   input_feature_map_array=reader,
                                                   conv=("conv",3,1,1),
                                                   max_pool=("None",(None,None),(None,None)),
                                                   relu=("relu",None),             
                                                   batch=("batch",4,("weight",512,256,9),("gamma"),("variance"),("mean"),("beta")),
                                                   output_channel=512,
                                                   branch_node = None
                                                   )

np.save('floating_answer5', floating_answer5)
np.save('fixed_answer5', fixed_answer5)
'''
floating_answer5 = np.load("OCR_floating_answer/floating_answer5.npy")
fixed_answer5 = np.load("OCR_fixed_answer/fixed_answer5.npy")
print(floating_answer5)


[[[ 0.02248102  0.02248102  0.02248102 ...  0.02248102  0.02248102
    0.02248102]
  [ 0.02248102  0.02248102  0.02248102 ...  0.02248102  0.02248102
    0.02248102]
  [ 0.02248102  0.02248102  0.02248102 ...  0.02248102  0.02248102
    0.02248102]
  [ 0.02248102  0.02248102  0.02248102 ...  0.02248102  0.02248102
    0.02248102]]

 [[ 0.03915348  0.03915348  0.03915348 ...  0.03915348  0.03915348
    0.03915348]
  [ 0.03915348  0.03915348  0.03915348 ...  0.03915348  0.03915348
    0.03915348]
  [ 1.05128387  0.03915348  0.03915348 ...  0.03915348  0.03915348
    0.03915348]
  [ 1.7601065   0.03915348  0.03915348 ...  0.03915348  0.03915348
    0.03915348]]

 [[ 0.03933268  0.03933268  0.03933268 ...  0.03933268  0.03933268
    0.03933268]
  [ 0.03933268  0.03933268  0.03933268 ...  0.03933268  0.03933268
    0.03933268]
  [ 0.03933268  0.03933268  0.03933268 ...  0.03933268  0.03933268
    0.03933268]
  [ 0.25790228  0.03933268  2.52538078 ...  0.03933268  0.03933268
    0.03933268]]

In [12]:
reader = {}
reader["floating_answer"] = floating_answer5
reader["fixed_answer"]    = fixed_answer5
TODO_LIST = ["conv","relu","batch","max_pool"]
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#check your API and change your weight to lstm
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  

In [13]:
'''
floating_answer6 , fixed_answer6 , float_node6 , fixed_node6= layer_information(TODO_List=TODO_LIST,
                                                   layer_number="layer6",
                                                   input_feature_map_array=reader,
                                                   conv=("conv",3,1,1),
                                                   max_pool=("max_pool",(2,2),(2,2)),
                                                   relu=("relu",None),             
                                                   batch=("batch",5,("weight",512,512,9),("gamma"),("variance"),("mean"),("beta")),
                                                   output_channel=512,
                                                   branch_node = None
                                                   )
np.save('floating_answer6', floating_answer6)
np.save('fixed_answer6', fixed_answer6)
'''
floating_answer6 = np.load("OCR_floating_answer/floating_answer6.npy")
fixed_answer6 = np.load("OCR_fixed_answer/fixed_answer6.npy")
print(floating_answer6)


[[[-7.70005082e-02 -7.70005082e-02  2.80973844e+00 ...  3.07572929e-01
    3.08273226e-01  3.26585891e-01]
  [ 1.29568481e+00 -7.70005082e-02 -7.70005082e-02 ... -7.70005082e-02
   -7.70005082e-02  1.48615941e-01]]

 [[-9.30517825e-02 -9.30517825e-02 -9.30517825e-02 ... -9.30517825e-02
   -6.06889100e-02 -1.56441489e-02]
  [-9.30517825e-02 -9.30517825e-02 -9.30517825e-02 ... -9.30517825e-02
   -9.30517825e-02 -6.79604440e-02]]

 [[ 2.71385036e-02  2.71385036e-02  2.71385036e-02 ...  2.71385036e-02
    2.71385036e-02  1.47432779e-01]
  [ 2.71385036e-02  2.71385036e-02  2.71385036e-02 ...  2.71385036e-02
    2.71385036e-02  1.25468765e-01]]

 ...

 [[-1.12184305e-01 -1.12184305e-01 -1.12184305e-01 ... -2.61543875e-02
    4.91058306e-03  5.45631117e-02]
  [-1.12184305e-01 -1.12184305e-01 -1.12184305e-01 ... -1.12184305e-01
   -9.52196385e-02 -1.50273451e-02]]

 [[ 9.50884085e+00 -3.81913626e-02 -3.81913626e-02 ...  3.38868695e-02
    1.32671430e-01  2.02265211e-01]
  [-3.81913626e-02 -3.8

In [14]:
reader = {}
reader["floating_answer"] = floating_answer6
reader["fixed_answer"]    = fixed_answer6
TODO_LIST = ["conv","relu"]
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#check your API and change your weight to lstm
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  

In [15]:
'''
floating_answer7 , fixed_answer7 , float_node7 , fixed_node7= layer_information(TODO_List=TODO_LIST,
                                                   layer_number="layer7",
                                                   input_feature_map_array=reader,
                                                   conv=("conv",2,1,0),
                                                   max_pool=("None",(None,None),(None,None)),
                                                   relu=("relu",None),             
                                                   batch=("batch",6,("weight",512,512,4),("bias")),
                                                   output_channel=512,
                                                   branch_node = None
                                                   )
np.save('floating_answer7', floating_answer7)
np.save('fixed_answer7', fixed_answer7)
'''
floating_answer7 = np.load("OCR_floating_answer/floating_answer7.npy")
fixed_answer7 = np.load("OCR_fixed_answer/fixed_answer7.npy")

print(floating_answer7[2])
print(floating_answer7.shape)


[[0.         0.         1.84984613 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.12609721 0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.        ]]
(512, 1, 31)


In [16]:
'''
print(floating_answer7.shape)
print(fixed_answer7.shape)
floating_answer8 = squeeze(floating_answer7,dim=1)
fixed_answer8 = squeeze(fixed_answer7,dim=1)
np.save('floating_answer8', floating_answer8)
np.save('fixed_answer8', fixed_answer8)
'''
floating_answer8 = np.load("OCR_floating_answer/floating_answer8.npy")
fixed_answer8 = np.load("OCR_fixed_answer/fixed_answer8.npy")
print(floating_answer8.shape)


(31, 512)


In [17]:
float_lstm_answer1 , fixed_lstm_answer1 = LSTM(fixed_layer = fixed_answer8     ,float_layer=floating_answer8  ,file_number=6,units=128,xt_shape=(512,512),ht_shape=(128,512),dir_choose=1)
#print(fixed_lstm_answer1)
#print(float_lstm_answer1)
float_lstm_answer2 , fixed_lstm_answer2 = LSTM(fixed_layer = fixed_lstm_answer1,float_layer=float_lstm_answer1,file_number=1,units=128,xt_shape=(128,512),ht_shape=(128,512),dir_choose=2)
#print(fixed_lstm_answer2)
#print(float_lstm_answer2)

f_bias file is open and read
f_x file is open and read
f_h file is open and read
the list of mse_array is [0.27318670427759]
the most value in mse_array is 0.27318670427759
the most value in mse_array index is << 1
(31, 128)
f_bias file is open and read
f_x file is open and read
f_h file is open and read
the list of mse_array is [0.348935256494206]
the most value in mse_array is 0.348935256494206
the most value in mse_array index is << 1
(31, 128)


In [18]:
def greedy(pred):
    pred_result = np.argmax(pred,axis=-1)
    new_labels = []
    previous = None
    for l in pred_result:
        if l != previous:
            new_labels.append(l)
            previous = l
    new_labels = [l for l in new_labels if int(l) < len(char_list)]
    return new_labels

In [20]:
Dense_float_result , Dense_fixed_result= Dense(units=63,file_number=1,float_layer=float_lstm_answer2,fixed_layer=fixed_lstm_answer2,weight_shape=(128,63),bias_shape=(1,63),relu_type="relu")
Dense_float_answer = np.argmax(Dense_float_result,axis=-1)
Dense_fixed_answer = np.argmax(Dense_fixed_result,axis=-1)
print("\nfloat每一個cell特徵值")
print(Dense_float_result)
print("\nfixed每一個cell特徵值")
print(Dense_fixed_result)
print("\nfloat每一個cell特徵最大值index")
print(Dense_float_answer)
print("\nfixed每一個cell特徵最大值index")
print(Dense_fixed_answer)
char_list = string.ascii_letters + string.digits
print("\n-------------------prediction-----------------\n")
print(greedy(Dense_float_result))
output = greedy(Dense_float_result)
for x in output:
    print("float_predicted_text =  ", end = '')
    if int(x) < 62 and int(x)!=-1:
        print(char_list[int(x)], end = '')       
    print('\n')
print("--------------------------------------")
print(greedy(Dense_fixed_result))
output = greedy(Dense_fixed_result)
for x in output:
    print("fixed_predicted_text =  ", end = '')
    if int(x) < 62 and int(x)!=-1:
        print(char_list[int(x)], end = '')       
    print('\n')

weight file is open and read
bias file is open and read
the list of mse_array is [6.943462865841262]
the most value in mse_array is 6.943462865841262
the most value in mse_array index is << 1

float每一個cell特徵值
[[ 0.          2.35893818  0.         ...  0.          0.
   0.61504283]
 [ 1.47105467  0.          0.         ...  0.94706346  0.
   6.4515572 ]
 [ 0.          2.55970862  0.         ...  0.          0.
   4.11304213]
 ...
 [ 0.          0.          0.         ...  0.          0.
  18.83512609]
 [ 0.          0.          0.         ...  0.          0.
  18.86633374]
 [ 0.          0.          0.         ...  0.          0.
  18.23100538]]

fixed每一個cell特徵值
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

float每一個cell特徵最大值index
[29 30 41 43 30 30 28 26 45 62 30 29 29 62 62 62 62 62 62 62 62 62 62 62
 62 62 62 62 62 62 62]

fixed每一個cell特徵最大值index
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0