In [1]:
from pola_fixed_point_API import *
import string

In [2]:
reader = {}
#down_dim = np.squeeze(read_gray_picture_from_txt("./lstm_input_feature_map/0.txt",(32,128,1)),axis=-1) 
#up_dim = np.expand_dims(down_dim,axis=0)
#reader["floating_answer"] = up_dim
reader["floating_answer"] = read_picture_from_jpg("./lstm_input_feature_map/SMART_input_feature_map_0.csv",gray_type=True)
reader["fixed_answer"]    = np.array([0])
TODO_LIST = ["conv","relu"]
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#check your API and change your weight to lstm
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  

In [3]:
'''
floating_answer1 , fixed_answer1 , float_node1 , fixed_node1= layer_information(TODO_List=TODO_LIST,
                                                   layer_number="layer1",
                                                   input_feature_map_array=reader,
                                                   conv=("conv",3,1,1),
                                                   max_pool=("None",(None,None),(None,None)),
                                                   relu=("relu",None),
                                                   #relu=("None",None),              
                                                   batch=("batch",0,("weight",4,1,9),("bias")),
                                                   output_channel=4,
                                                   branch_node = None
                                                   )
np.save('SMART_floating_answer/floating_answer1', floating_answer1)
np.save('SMART_fixed_answer/fixed_answer1', fixed_answer1)
'''
floating_answer1 = np.load("SMART_floating_answer/floating_answer1.npy")
fixed_answer1 = np.load("SMART_fixed_answer/fixed_answer1.npy")

print(floating_answer1)


[[[3.54867127e-03 1.67447273e-03 1.63545183e-03 ... 3.03930647e-05
   2.82960053e-05 3.54117711e-05]
  [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 2.63699846e-05
   2.71592293e-05 3.25636569e-05]
  [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 2.54506332e-05
   2.77818967e-05 3.22546473e-05]
  ...
  [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 1.93987603e-05
   2.03018456e-05 2.81580041e-05]
  [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 1.57900742e-05
   1.69565871e-05 2.68054476e-05]
  [3.76095789e-03 3.60992644e-03 3.27702734e-03 ... 4.96227648e-05
   4.81575673e-05 3.83122913e-05]]

 [[1.44770830e-03 6.29590239e-03 9.25196720e-03 ... 3.22787497e-03
   3.21775594e-03 3.22097434e-03]
  [3.40132386e-03 8.93454193e-03 1.41997904e-02 ... 3.22932266e-03
   3.22010485e-03 3.22232038e-03]
  [2.17265648e-03 7.40962581e-03 1.53610817e-02 ... 3.22951109e-03
   3.22026474e-03 3.22318142e-03]
  ...
  [6.40804492e-04 5.53086259e-03 1.75059266e-02 ... 3.23656530e-03
   3.23570

In [4]:
reader = {}
reader["floating_answer"] = floating_answer1
reader["fixed_answer"]    = fixed_answer1
TODO_LIST = ["conv","relu"]
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#check your API and change your weight to lstm
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  

In [5]:
'''
floating_answer2 , fixed_answer2 , float_node2 , fixed_node2= layer_information(TODO_List=TODO_LIST,
                                                   layer_number="layer2",
                                                   input_feature_map_array=reader,
                                                   conv=("conv",3,1,1),
                                                   max_pool=("None",(None,None),(None,None)),
                                                   relu=("relu",None),
                                                   batch=("batch",1,("weight",8,4,9),("bias")),
                                                   output_channel=8,
                                                   branch_node = None
                                                   )
np.save('SMART_floating_answer/floating_answer2', floating_answer2)
np.save('SMART_fixed_answer/fixed_answer2', fixed_answer2)
'''
floating_answer2 = np.load("SMART_floating_answer/floating_answer2.npy")
fixed_answer2 = np.load("SMART_fixed_answer/fixed_answer2.npy")
print(floating_answer2)


[[[0.00193829 0.00201308 0.00293766 ... 0.00348561 0.00348314 0.00458498]
  [0.00241349 0.00120269 0.00169874 ... 0.00387065 0.00386921 0.00444094]
  [0.00282896 0.00350831 0.00442472 ... 0.00387108 0.00386914 0.00444048]
  ...
  [0.00240277 0.00634925 0.00600187 ... 0.00386828 0.00386693 0.00444485]
  [0.00319291 0.00805052 0.00692415 ... 0.00386924 0.0038635  0.00443791]
  [0.00451926 0.00940363 0.00699597 ... 0.00449327 0.00449195 0.00411139]]

 [[0.00375263 0.00835153 0.01087105 ... 0.00492417 0.00492019 0.00516371]
  [0.00551621 0.01218179 0.01351496 ... 0.00588469 0.00587976 0.00518514]
  [0.00566194 0.0137854  0.01429522 ... 0.00588328 0.00587926 0.00518504]
  ...
  [0.00428976 0.01625308 0.01408246 ... 0.00589089 0.0058962  0.00518973]
  [0.00397346 0.0161252  0.0143459  ... 0.00589215 0.00589687 0.00519172]
  [0.00537272 0.01099579 0.00869408 ... 0.00561908 0.00562322 0.00398371]]

 [[0.00320441 0.0024684  0.00133349 ... 0.00155266 0.0015551  0.00314958]
  [0.005235   0.002911

In [6]:
reader = {}
reader["floating_answer"] = floating_answer2
reader["fixed_answer"]    = fixed_answer2
TODO_LIST = ["conv","relu"]
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#check your API and change your weight to lstm
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  

In [7]:
'''
floating_answer3 , fixed_answer3 , float_node3 , fixed_node3= layer_information(TODO_List=TODO_LIST,
                                                   layer_number="layer3",
                                                   input_feature_map_array=reader,
                                                   conv=("conv",3,1,1),
                                                   max_pool=("None",(None,None),(None,None)),
                                                   relu=("relu",None),  
                                                   batch=("batch",2,("weight",16,8,9),("bias")),
                                                   output_channel=16,
                                                   branch_node = None
                                                   )
np.save('SMART_floating_answer/floating_answer3', floating_answer3)
np.save('SMART_fixed_answer/fixed_answer3', fixed_answer3)
'''
floating_answer3 = np.load("SMART_floating_answer/floating_answer3.npy")
fixed_answer3 = np.load("SMART_fixed_answer/fixed_answer3.npy")
print(floating_answer3)


[[[0.00465009 0.00387817 0.00351171 ... 0.00429156 0.00409282 0.00217022]
  [0.0051703  0.00287459 0.0019738  ... 0.00434228 0.00460995 0.00197964]
  [0.00456685 0.00275263 0.00248613 ... 0.00462857 0.00455379 0.00181391]
  ...
  [0.00484649 0.00202122 0.00195043 ... 0.0046268  0.00454881 0.00181224]
  [0.00514668 0.00229901 0.0035639  ... 0.00478126 0.00450088 0.00197161]
  [0.00416769 0.00221608 0.00502112 ... 0.00406739 0.00414709 0.00340711]]

 [[0.00074519 0.         0.         ... 0.0019702  0.00189542 0.0025885 ]
  [0.00096803 0.00176701 0.         ... 0.00399987 0.00384915 0.00515973]
  [0.         0.00302008 0.00054997 ... 0.00369906 0.0038218  0.00522967]
  ...
  [0.         0.00476818 0.00362445 ... 0.00369551 0.00381853 0.00522961]
  [0.         0.00485222 0.00481913 ... 0.00369183 0.00375226 0.00522429]
  [0.00176555 0.00642651 0.00896107 ... 0.00485408 0.00491055 0.005604  ]]

 [[0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.      

In [8]:
reader = {}
reader["floating_answer"] = floating_answer3
reader["fixed_answer"]    = fixed_answer3
TODO_LIST = ["conv","relu","max_pool"]
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#check your API and change your weight to lstm
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  

In [9]:
'''
floating_answer4 , fixed_answer4 , float_node4 , fixed_node4= layer_information(TODO_List=TODO_LIST,
                                                   layer_number="layer4",
                                                   input_feature_map_array=reader,
                                                   conv=("conv",3,1,1),
                                                   max_pool=("max_pool",(2,2),(2,2)),
                                                   relu=("relu",None),
                                                   batch=("batch",3,("weight",16,16,9),("bias")),
                                                   output_channel=16,
                                                   branch_node = None
                                                   )
np.save('SMART_floating_answer/floating_answer4', floating_answer4)
np.save('SMART_fixed_answer/fixed_answer4', fixed_answer4)
'''
floating_answer4 = np.load("SMART_floating_answer/floating_answer4.npy")
fixed_answer4 = np.load("SMART_fixed_answer/fixed_answer4.npy")
print(floating_answer4)


[[[3.41283133e-03 1.77287040e-03 1.85871341e-03 ... 4.20843112e-03
   4.32956223e-03 6.78007628e-03]
  [3.89483289e-03 4.98142765e-03 5.80520013e-03 ... 3.85900523e-03
   4.05090467e-03 6.55870410e-03]
  [3.91550185e-03 4.34805846e-03 6.02324969e-03 ... 3.86146412e-03
   4.05125535e-03 6.55858646e-03]
  ...
  [4.93899292e-03 2.40643122e-03 6.26094153e-03 ... 3.86373195e-03
   4.04977802e-03 6.55738837e-03]
  [4.00164528e-03 4.61766856e-03 5.24942148e-03 ... 3.86686620e-03
   4.04950277e-03 6.55763749e-03]
  [5.17374103e-03 6.59057441e-03 6.71960734e-03 ... 5.33485252e-03
   5.58434963e-03 6.40356534e-03]]

 [[2.22374370e-02 2.31499091e-02 2.09520057e-02 ... 1.96011945e-02
   1.96005836e-02 1.98361126e-02]
  [2.66369230e-02 2.62548117e-02 2.14112883e-02 ... 2.16906020e-02
   2.16921743e-02 2.16540141e-02]
  [2.77984379e-02 2.61637365e-02 2.26882408e-02 ... 2.16927099e-02
   2.16919905e-02 2.16536292e-02]
  ...
  [2.82460940e-02 2.49019890e-02 2.15956802e-02 ... 2.16954513e-02
   2.16888

In [10]:
reader = {}
reader["floating_answer"] = floating_answer4
reader["fixed_answer"]    = fixed_answer4
TODO_LIST = ["conv","relu"]
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#check your API and change your weight to lstm
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  

In [11]:
'''
floating_answer5 , fixed_answer5 , float_node5 , fixed_node5= layer_information(TODO_List=TODO_LIST,
                                                   layer_number="layer5",
                                                   input_feature_map_array=reader,
                                                   conv=("conv",3,1,1),
                                                   max_pool=("None",(None,None),(None,None)),
                                                   relu=("relu",None),             
                                                   batch=("batch",4,("weight",32,16,9),("bias")),
                                                   output_channel=32,
                                                   branch_node = None
                                                   )
np.save('SMART_floating_answer/floating_answer5', floating_answer5)
np.save('SMART_fixed_answer/fixed_answer5', fixed_answer5)
'''
floating_answer5 = np.load("SMART_floating_answer/floating_answer5.npy")
fixed_answer5 = np.load("SMART_fixed_answer/fixed_answer5.npy")
print(floating_answer5)


[[[0.00537596 0.00758979 0.00851877 ... 0.00687369 0.00729842 0.00942392]
  [0.00964786 0.01031377 0.01077053 ... 0.0089819  0.0094635  0.00856495]
  [0.01020975 0.0099499  0.01043063 ... 0.00908534 0.00965821 0.00835636]
  ...
  [0.01021945 0.01134624 0.01023492 ... 0.00900238 0.00960855 0.00832593]
  [0.01050085 0.01119153 0.01033998 ... 0.00890274 0.00949577 0.00837439]
  [0.0082211  0.00688844 0.00611974 ... 0.0055761  0.00586338 0.00309024]]

 [[0.00712784 0.01083282 0.0102591  ... 0.00921866 0.00907351 0.00497445]
  [0.00437662 0.014678   0.01460222 ... 0.01232607 0.01236359 0.01026492]
  [0.00417424 0.01606965 0.01598799 ... 0.01221482 0.01238406 0.01047897]
  ...
  [0.00485782 0.01586137 0.01463338 ... 0.01227891 0.01242565 0.01048325]
  [0.00436742 0.01687271 0.01579965 ... 0.01263833 0.01265995 0.01081792]
  [0.00145139 0.01067244 0.01160507 ... 0.00798803 0.00821664 0.00822948]]

 [[0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.      

In [12]:
reader = {}
reader["floating_answer"] = floating_answer5
reader["fixed_answer"]    = fixed_answer5
TODO_LIST = ["conv","relu","max_pool"]
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#check your API and change your weight to lstm
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  

In [13]:
'''
floating_answer6 , fixed_answer6 , float_node6 , fixed_node6= layer_information(TODO_List=TODO_LIST,
                                                   layer_number="layer6",
                                                   input_feature_map_array=reader,
                                                   conv=("conv",3,1,1),
                                                   max_pool=("max_pool",(2,2),(2,2)),
                                                   relu=("relu",None),             
                                                   batch=("batch",5,("weight",64,32,9),("bias")),
                                                   output_channel=64,
                                                   branch_node = None
                                                   )
np.save('SMART_floating_answer/floating_answer6', floating_answer6)
np.save('SMART_fixed_answer/fixed_answer6', fixed_answer6)
'''
floating_answer6 = np.load("SMART_floating_answer/floating_answer6.npy")
fixed_answer6 = np.load("SMART_fixed_answer/fixed_answer6.npy")
print(floating_answer6)


[[[8.58855751e-03 1.08865638e-02 1.11951966e-02 ... 1.04858754e-02
   1.05353698e-02 8.49860473e-03]
  [1.26499531e-02 1.41805243e-02 1.45164503e-02 ... 1.31396421e-02
   1.33308779e-02 9.44517735e-03]
  [1.20996706e-02 1.50039837e-02 1.54061298e-02 ... 1.31156202e-02
   1.33078481e-02 9.30476351e-03]
  ...
  [1.13797237e-02 1.56310071e-02 1.62803343e-02 ... 1.31163568e-02
   1.33082204e-02 9.30435749e-03]
  [1.15223834e-02 1.47805777e-02 1.62984158e-02 ... 1.31173045e-02
   1.33082878e-02 9.30868172e-03]
  [1.36577731e-02 1.62962793e-02 1.64137119e-02 ... 1.39134785e-02
   1.42251389e-02 1.21556864e-02]]

 [[4.99171031e-03 6.44269625e-03 5.53888949e-03 ... 5.32742961e-03
   5.48192705e-03 7.84527787e-03]
  [3.64461460e-03 5.42044751e-03 5.40012183e-03 ... 4.96232366e-03
   5.08961581e-03 7.81117226e-03]
  [3.05731711e-03 4.98563346e-03 4.82863833e-03 ... 4.81616790e-03
   4.96289049e-03 7.66593060e-03]
  ...
  [2.99632282e-03 4.84894283e-03 4.52329328e-03 ... 4.81645848e-03
   4.96224

In [14]:
reader = {}
reader["floating_answer"] = floating_answer6
reader["fixed_answer"]    = fixed_answer6
TODO_LIST = ["conv","relu","max_pool"]
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#check your API and change your weight to lstm
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  

In [15]:
'''
floating_answer7 , fixed_answer7 , float_node7 , fixed_node7= layer_information(TODO_List=TODO_LIST,
                                                   layer_number="layer7",
                                                   input_feature_map_array=reader,
                                                   conv=("conv",3,1,1),
                                                   max_pool=("max_pool",(2,2),(2,2)),
                                                   relu=("relu",None),             
                                                   batch=("batch",6,("weight",64,64,9),("bias")),
                                                   output_channel=64,
                                                   branch_node = None
                                                   )
np.save('SMART_floating_answer/floating_answer7', floating_answer7)
np.save('SMART_fixed_answer/fixed_answer7', fixed_answer7)
'''
floating_answer7 = np.load("SMART_floating_answer/floating_answer7.npy")
fixed_answer7 = np.load("SMART_fixed_answer/fixed_answer7.npy")
print(floating_answer7)


[[[0.02230297 0.02475164 0.02559986 ... 0.02385134 0.02384971 0.02930649]
  [0.02376901 0.02587747 0.02616946 ... 0.02385731 0.02385597 0.03004262]
  [0.02283874 0.02598824 0.02622595 ... 0.02385723 0.02385494 0.030023  ]
  ...
  [0.02335135 0.02719985 0.02819523 ... 0.02385724 0.02385533 0.03002163]
  [0.02342228 0.02667636 0.02802238 ... 0.02385698 0.02385552 0.03005953]
  [0.02197726 0.0271588  0.02772224 ... 0.02382009 0.02381895 0.03018544]]

 [[0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.         0.         ... 0.         0.         0.        ]
  ...
  [0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.         0.         ... 0.         0.         0.        ]]

 [[0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.      

In [16]:
reader = {}
reader["floating_answer"] = floating_answer7
reader["fixed_answer"]    = fixed_answer7
TODO_LIST = ["conv","relu","max_pool"]
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#check your API and change your weight to lstm
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  

In [17]:
'''
floating_answer8 , fixed_answer8 , float_node8 , fixed_node8= layer_information(TODO_List=TODO_LIST,
                                                   layer_number="layer8",
                                                   input_feature_map_array=reader,
                                                   conv=("conv",3,1,1),
                                                   max_pool=("max_pool",(2,2),(2,2)),
                                                   relu=("relu",None),             
                                                   batch=("batch",7,("weight",64,64,9),("bias")),
                                                   output_channel=64,
                                                   branch_node = None
                                                   )
np.save('SMART_floating_answer/floating_answer8', floating_answer8)
np.save('SMART_fixed_answer/fixed_answer8', fixed_answer8)
'''
floating_answer8 = np.load("SMART_floating_answer/floating_answer8.npy")
fixed_answer8 = np.load("SMART_fixed_answer/fixed_answer8.npy")
print(floating_answer8)


[[[0.03905064 0.04102003 0.03897462 ... 0.03365922 0.03370457 0.03329751]
  [0.04026629 0.04042857 0.03876083 ... 0.03311452 0.03316404 0.03246824]
  [0.03993067 0.04068535 0.03907347 ... 0.03311777 0.03316419 0.03246775]
  ...
  [0.04363308 0.04195992 0.03898207 ... 0.03311548 0.03316446 0.03246601]
  [0.0414965  0.04141553 0.03904442 ... 0.03314695 0.03319217 0.03249502]
  [0.04023368 0.0405848  0.03812628 ... 0.03266489 0.03270808 0.03192655]]

 [[0.04397639 0.04867745 0.04077499 ... 0.03730008 0.03734442 0.03909023]
  [0.04300158 0.04962689 0.04115328 ... 0.03728231 0.03732367 0.03972054]
  [0.04363404 0.04948392 0.04129259 ... 0.03726443 0.03730367 0.03970114]
  ...
  [0.04294835 0.05009865 0.0415602  ... 0.03726729 0.03730342 0.03970195]
  [0.04649067 0.05101613 0.04148758 ... 0.03730968 0.03734119 0.03973152]
  [0.04712653 0.05115581 0.04120793 ... 0.03764555 0.03766981 0.03955464]]

 [[0.02126822 0.02563602 0.0248429  ... 0.02047604 0.02046924 0.0234466 ]
  [0.01632319 0.023515

In [18]:
reader = {}
reader["floating_answer"] = floating_answer8
reader["fixed_answer"]    = fixed_answer8
TODO_LIST = ["conv","relu","max_pool"]
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#check your API and change your weight to lstm
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  

In [19]:
'''
floating_answer9 , fixed_answer9 , float_node9 , fixed_node9= layer_information(TODO_List=TODO_LIST,
                                                   layer_number="layer9",
                                                   input_feature_map_array=reader,
                                                   conv=("conv",3,1,1),
                                                   max_pool=("max_pool",(2,2),(2,2)),
                                                   relu=("relu",None),             
                                                   batch=("batch",8,("weight",128,64,9),("bias")),
                                                   output_channel=128,
                                                   branch_node = None
                                                   )
np.save('SMART_floating_answer/floating_answer9', floating_answer9)
np.save('SMART_fixed_answer/fixed_answer9', fixed_answer9)
'''
floating_answer9 = np.load("SMART_floating_answer/floating_answer9.npy")
fixed_answer9 = np.load("SMART_fixed_answer/fixed_answer9.npy")
print(floating_answer9)


[[[0.05849282 0.05377125 0.04821478 ... 0.04513486 0.04511266 0.04588994]
  [0.05752862 0.05323256 0.04711436 ... 0.0440471  0.04402983 0.0446404 ]
  [0.05739844 0.05284556 0.04713897 ... 0.04402296 0.04401568 0.04462371]
  ...
  [0.05771402 0.05234083 0.04702608 ... 0.04402721 0.04401582 0.04461963]
  [0.05917175 0.05314591 0.04703752 ... 0.0440365  0.0440254  0.04463125]
  [0.05537604 0.05092149 0.04551031 ... 0.04304117 0.04304478 0.04308671]]

 [[0.08656795 0.08324225 0.0730639  ... 0.06862546 0.06860296 0.07014489]
  [0.09079226 0.0860625  0.07612601 ... 0.07106371 0.07103858 0.07222816]
  [0.09148936 0.08605055 0.07584585 ... 0.07103889 0.07102948 0.07221336]
  ...
  [0.09114183 0.08587234 0.07568237 ... 0.07104174 0.07103025 0.07221343]
  [0.09354267 0.0860296  0.07590262 ... 0.07106625 0.07106119 0.07224524]
  [0.09433291 0.08851242 0.07780172 ... 0.07287949 0.0728659  0.07491218]]

 [[0.05864787 0.05232532 0.04904931 ... 0.04643726 0.04642569 0.04672618]
  [0.06124664 0.055149

In [20]:
reader = {}
reader["floating_answer"] = floating_answer9
reader["fixed_answer"]    = fixed_answer9
TODO_LIST = ["conv","relu","max_pool"]
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#check your API and change your weight to lstm
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  

In [21]:
'''
floating_answer10 , fixed_answer10 , float_node10 , fixed_node10= layer_information(TODO_List=TODO_LIST,
                                                   layer_number="layer10",
                                                   input_feature_map_array=reader,
                                                   conv=("conv",3,1,1),
                                                   max_pool=("max_pool",(2,2),(2,2)),
                                                   relu=("relu",None),             
                                                   batch=("batch",9,("weight",128,128,9),("bias")),
                                                   output_channel=128,
                                                   branch_node = None
                                                   )
np.save('SMART_floating_answer/floating_answer10', floating_answer10)
np.save('SMART_fixed_answer/fixed_answer10', fixed_answer10)
'''
floating_answer10 = np.load("SMART_floating_answer/floating_answer10.npy")
fixed_answer10 = np.load("SMART_fixed_answer/fixed_answer10.npy")
print(floating_answer10)


[[[0.08544094 0.08047596 0.07312735 ... 0.06998055 0.0699296  0.07345368]
  [0.08453614 0.07852835 0.07073418 ... 0.0675579  0.06750477 0.07300865]
  [0.08401519 0.07828046 0.07072858 ... 0.06754849 0.06749328 0.07301195]
  [0.08707289 0.08066527 0.07293536 ... 0.06967366 0.06961417 0.07398616]]

 [[0.33662767 0.31502117 0.3009284  ... 0.29108183 0.29089126 0.29208741]
  [0.32543599 0.30175944 0.2881545  ... 0.27844993 0.27825934 0.27980173]
  [0.32405018 0.30088731 0.28803103 ... 0.27843811 0.27822325 0.27978041]
  [0.32793421 0.30296433 0.28945941 ... 0.27988415 0.279668   0.28132295]]

 [[0.09395767 0.05980278 0.05983523 ... 0.05802125 0.05798806 0.0599327 ]
  [0.0435784  0.01352528 0.01391168 ... 0.01371413 0.01372021 0.01655986]
  [0.0431091  0.01343901 0.01387678 ... 0.01370898 0.01372331 0.01655903]
  [0.0495057  0.01920929 0.01963754 ... 0.01923391 0.01925063 0.02147256]]

 ...

 [[0.17426    0.15904907 0.14561316 ... 0.13986103 0.1397686  0.1400872 ]
  [0.1715772  0.15711342 0

In [22]:
reader = {}
reader["floating_answer"] = floating_answer10
reader["fixed_answer"]    = fixed_answer10
TODO_LIST = ["conv","relu"]
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#check your API and change your weight to lstm
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  

In [23]:
'''
floating_answer11 , fixed_answer11 , float_node11 , fixed_node11= layer_information(TODO_List=TODO_LIST,
                                                   layer_number="layer11",
                                                   input_feature_map_array=reader,
                                                   conv=("conv",3,1,1),
                                                   max_pool=("None",(None,None),(None,None)),
                                                   relu=("relu",None),             
                                                   batch=("batch",10,("weight",128,128,9),("bias")),
                                                   output_channel=128,
                                                   branch_node = None
                                                   )
np.save('SMART_floating_answer/floating_answer11', floating_answer11)
np.save('SMART_fixed_answer/fixed_answer11', fixed_answer11)
'''
floating_answer11 = np.load("SMART_floating_answer/floating_answer11.npy")
fixed_answer11 = np.load("SMART_fixed_answer/fixed_answer11.npy")
print(floating_answer11)


[[[0.31738189 0.50639513 0.48219021 ... 0.44978237 0.45208006 0.3015933 ]
  [0.36818524 0.51646283 0.49429534 ... 0.46372602 0.46960647 0.29630953]
  [0.3619327  0.52262824 0.5012782  ... 0.46942944 0.47685502 0.30517459]
  [0.35061351 0.43514976 0.41932638 ... 0.39682927 0.40170574 0.26893036]]

 [[0.         0.20168828 0.19122094 ... 0.17296435 0.17277261 0.24931473]
  [0.0841383  0.32191363 0.3060379  ... 0.28156228 0.28112765 0.30102489]
  [0.0860359  0.33143083 0.31517322 ... 0.28937472 0.2886783  0.3114363 ]
  [0.04423144 0.21280861 0.19946309 ... 0.18281268 0.18688824 0.18607662]]

 [[0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.         0.         ... 0.         0.         0.        ]]

 ...

 [[0.22809401 0.29413979 0.29462863 ... 0.27795317 0.27417229 0.1357592 ]
  [0.26351235 0.34685955 0

In [24]:
print(floating_answer11.shape)
print(fixed_answer11.shape)
flatten_floating_answer = Flatten(floating_answer11)
flatten_fixed_answer = Flatten(fixed_answer11)
print(flatten_floating_answer.shape)
print(flatten_fixed_answer.shape)
print(floating_answer11)
print(flatten_floating_answer)

(128, 4, 16)
(128, 4, 16)
(8192,)
(8192,)
[[[0.31738189 0.50639513 0.48219021 ... 0.44978237 0.45208006 0.3015933 ]
  [0.36818524 0.51646283 0.49429534 ... 0.46372602 0.46960647 0.29630953]
  [0.3619327  0.52262824 0.5012782  ... 0.46942944 0.47685502 0.30517459]
  [0.35061351 0.43514976 0.41932638 ... 0.39682927 0.40170574 0.26893036]]

 [[0.         0.20168828 0.19122094 ... 0.17296435 0.17277261 0.24931473]
  [0.0841383  0.32191363 0.3060379  ... 0.28156228 0.28112765 0.30102489]
  [0.0860359  0.33143083 0.31517322 ... 0.28937472 0.2886783  0.3114363 ]
  [0.04423144 0.21280861 0.19946309 ... 0.18281268 0.18688824 0.18607662]]

 [[0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.         0.         ... 0.         0.         0.        ]]

 ...

 [[0.22809401 0.29413979 0.29462863 ... 0.27795317 0.27417

In [25]:
Dense_float_result , Dense_fixed_result= Dense(units=100,file_number=0,float_layer=flatten_floating_answer,fixed_layer=flatten_fixed_answer,weight_shape=(8192,100),bias_shape=(1,100),relu_type="relu")
print(Dense_float_result)

weight file is open and read
bias file is open and read
the list of mse_array is [13.61652113353541]
the most value in mse_array is 13.61652113353541
the most value in mse_array index is << 1
[[6.74750897 2.94774584 0.         0.         6.29755674 0.
  0.         0.         6.51642701 6.53394853 0.         0.86230397
  2.76791379 6.44309813 2.86350785 0.         0.         5.85112616
  0.         5.46539752 0.         0.         4.21546995 0.
  0.         6.20219531 0.         3.82417194 6.13037767 0.
  6.08636948 0.         0.         0.         6.04116277 0.
  0.         0.         3.24036716 0.         0.         0.
  0.         0.         0.         0.         5.87052996 0.
  0.         0.         4.84298731 6.63262153 0.         2.63559541
  0.         6.39220651 6.62142125 6.31063674 0.         0.
  0.         7.82182029 0.         0.         4.59254611 0.
  0.         0.         7.18446386 0.         0.         6.04670379
  4.95804062 0.         0.         5.39463792 0.        

In [26]:
Dense_float_result1 , Dense_fixed_result1= Dense(units=100,file_number=1,float_layer=Dense_float_result,fixed_layer=Dense_fixed_result,weight_shape=(100,100),bias_shape=(1,100),relu_type="relu")
print(Dense_float_result1)

weight file is open and read
bias file is open and read
the list of mse_array is [14.04426465592334]
the most value in mse_array is 14.04426465592334
the most value in mse_array index is << 1
[[2.35711303e+00 4.10602559e+00 9.52911525e+00 0.00000000e+00
  5.97647218e+00 8.20675063e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 7.28024805e+00 0.00000000e+00 0.00000000e+00
  2.40690394e+00 7.86901400e+00 3.59679947e+00 2.62996540e+00
  5.84305742e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 6.74402089e+00 8.53863559e+00 1.37799670e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 6.90863675e-01 8.93851536e-01
  0.00000000e+00 6.63313899e+00 6.47676409e+00 0.00000000e+00
  0.00000000e+00 1.95783792e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 1.85331611e+00 0.00000000e+00 4.60222106e+00
  0.00000000e+00 3.47137051e-02 6.31056425e+00 4.65748224e+00
  4.64843396e+00 8.64153248e+00 0.00000000e+00 0.00000000e+00
  

In [27]:
Dense_float_result2 , Dense_fixed_result2= Dense(units=100,file_number=2,float_layer=Dense_float_result1,fixed_layer=Dense_fixed_result1,weight_shape=(100,100),bias_shape=(1,100),relu_type="relu")
print(Dense_float_result2)

weight file is open and read
bias file is open and read
the list of mse_array is [10.45009301188256]
the most value in mse_array is 10.45009301188256
the most value in mse_array index is << 1
[[2.13491000e-03 5.43035439e-01 0.00000000e+00 0.00000000e+00
  5.25131015e+00 9.68335757e+00 3.43872911e+00 7.53270163e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 3.96432690e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  1.54785473e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 6.97024258e-01 2.44565680e+00
  2.44432106e+00 1.62810710e+00 6.68924271e+00 0.00000000e+00
  0.00000000e+00 7.64997710e+00 4.17341873e+00 0.00000000e+00
  0.00000000e+00 5.50806668e+00 0.00000000e+00 3.25746020e+00
  9.33051207e-01 0.00000000e+00 0.00000000e+00 2.94405463e+00
  1.71370734e+00 0.00000000e+00 0.00000000e+00 6.01723071e+00
  3.64027657e+00 0.00000000e+00 0.00000000e+00 1.78486211e+00
  3.99663761e+00 2.60745921e+00 0.00000000e+00 4.59452325e+00
  

In [28]:
Dense_float_result3 , Dense_fixed_result3= Dense(units=100,file_number=3,float_layer=Dense_float_result2,fixed_layer=Dense_fixed_result2,weight_shape=(100,100),bias_shape=(1,100),relu_type="relu")
print(Dense_float_result3)

weight file is open and read
bias file is open and read
the list of mse_array is [10.165364740603712]
the most value in mse_array is 10.165364740603712
the most value in mse_array index is << 1
[[5.17056579e+00 0.00000000e+00 6.59529331e+00 1.22602369e+00
  8.25671537e-01 0.00000000e+00 4.79405465e-01 7.38356060e+00
  8.47487335e-01 7.90510648e+00 3.50522687e+00 5.20766336e+00
  1.71546746e-03 0.00000000e+00 8.00100563e-01 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 8.80571302e+00
  0.00000000e+00 6.50794250e+00 0.00000000e+00 2.87802419e+00
  2.77851084e+00 0.00000000e+00 1.94186270e-01 2.31249163e+00
  1.17562944e+00 7.23874019e+00 7.23143141e+00 0.00000000e+00
  8.40831854e-01 2.12491564e+00 0.00000000e+00 0.00000000e+00
  5.60343045e+00 2.87993032e+00 2.07925638e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 1.11232186e+01
  6.56719284e+00 0.00000000e+00 0.00000000e+00 7.85088723e+00
  3.08308798e+00 1.86042768e-02 0.00000000e+00 2.41768752e+00


In [29]:
Dense_float_result4 , Dense_fixed_result4= Dense(units=100,file_number=4,float_layer=Dense_float_result3,fixed_layer=Dense_fixed_result3,weight_shape=(100,100),bias_shape=(1,100),relu_type="relu")
print(Dense_float_result4)

weight file is open and read
bias file is open and read
the list of mse_array is [7.870165460341251]
the most value in mse_array is 7.870165460341251
the most value in mse_array index is << 1
[[0.         0.         1.93907152 0.         6.00235045 0.
  0.         0.         1.789736   0.         0.         5.39564101
  0.         0.         3.41461892 0.         4.33862555 0.
  0.         0.43317196 0.2882834  0.         0.         0.
  0.         0.         6.54329061 5.14273899 0.         0.
  0.         0.         0.         0.         0.03722082 4.47458055
  2.1394209  0.         3.15915832 1.92322944 1.67492234 0.16351277
  2.76089153 0.         1.31102409 0.43231471 2.22418895 0.
  3.37310874 1.88932976 0.54260416 0.78875841 0.37329565 0.15238069
  0.         8.42996757 0.         0.79759891 6.42248546 3.85108446
  0.         0.         1.90270502 3.95045216 3.25714208 0.21435645
  0.         0.         0.         8.74675642 5.95986911 2.66375788
  0.         0.         0.      

In [30]:
Dense_float_result5 , Dense_fixed_result5= Dense(units=100,file_number=5,float_layer=Dense_float_result4,fixed_layer=Dense_fixed_result4,weight_shape=(100,1),bias_shape=(1,1),relu_type="relu")
print(Dense_float_result5)

weight file is open and read
bias file is open and read
the list of mse_array is [144.60654653227377]
the most value in mse_array is 144.60654653227377
the most value in mse_array index is << 1
[[12.02524622]]


In [31]:
dense_weight = read_parameter(file_serial="dense",file_name="weight",file_number=0)
dense_bias   = read_parameter(file_serial="dense",file_name="bias",file_number=0)
dense_weight = dense_weight.reshape(64,128,100)
dense_bias   = dense_bias.reshape(1,100)

weight file is open and read
bias file is open and read


In [32]:
flatten_floating_reshape = flatten_floating_answer.reshape(64,128)
flatten_floating_answer_tmp = np.zeros((64,144))
flatten_floating_answer_tmp[:,:128] = flatten_floating_reshape[:,:]
flatten_floating_answer_tmp = flatten_floating_answer_tmp.reshape(9216)
tmp_weight = np.zeros((64,144,120))
tmp_weight[:,:128,:100] = dense_weight[:,:,:]
tmp_weight = tmp_weight.reshape(9216,120)
tmp_bias = np.zeros((1,120))
tmp_bias[:,:100] = dense_bias[:,:]
answer = np.dot(flatten_floating_answer_tmp,tmp_weight) + tmp_bias
answer = nrelu(input_feature_map = answer, fixed_point = 0)
#------------test_weight_useing_hardware_func output_reuse------------------
x_total_round = int(120/24)
y_total_round = int(9216/24)
PE_array = 8
three_bank = 3
two_four_weight = 24
total_test_space = np.zeros([1,120])
total_weight_space = np.zeros([9216*120+240])
for x_side in range(x_total_round):
    for y_side in range(y_total_round):
        for bank in range(three_bank):
            for PE in range(PE_array):
                for count in range(two_four_weight):
                    x_jump_index = (bank*PE_array+PE) + x_side * 24
                    y_jump_index = y_side*24 + count
                    space_index = count + PE * two_four_weight * 3 + bank  * two_four_weight + y_side * 576 + x_side * y_total_round * 576 + x_side * 48
                    total_test_space[:,x_jump_index] = total_test_space[:,x_jump_index] + flatten_floating_answer_tmp[y_jump_index] * tmp_weight[y_jump_index][x_jump_index]
                    total_weight_space[space_index] = tmp_weight[y_jump_index][x_jump_index]
                    if(x_side==0 and y_side==0 and bank==0 and PE==3):
                        print("-----------------------------------")
                        print("input count_%d"%count)
                        print(flatten_floating_answer_tmp[y_jump_index])
                        print("-----weight-------")
                        print(tmp_weight[y_jump_index][x_jump_index])
                        print("-----calc_result----")
                        print(flatten_floating_answer_tmp[y_jump_index] * tmp_weight[y_jump_index][x_jump_index])
                        print("------------8_final_answer---------")
                        print(total_test_space[:,x_jump_index])
                        print("-----------------------------------")
                #print(total_test_space[:,x_jump_index])
    for alpha_index in range(two_four_weight):
        alpha_space_index = x_side * y_total_round * 576 + x_side * 48 + y_total_round * 576 + alpha_index
        total_weight_space[alpha_space_index] = 1
    for beta_index in range(two_four_weight):
        beta_space_index = x_side * y_total_round * 576 + x_side * 48 + y_total_round * 576 + 24 + beta_index
        total_weight_space[beta_space_index] = tmp_bias[:,x_side * two_four_weight + beta_index]
hw_answer = nrelu(input_feature_map = total_test_space + tmp_bias, fixed_point = 0)
#print(hw_answer)
try:
    os.stat("./"+fix_point_dir+"/total_weight_space/")
except:
    os.mkdir("./"+fix_point_dir+"/total_weight_space/")
with open("./"+fix_point_dir+"/total_weight_space"+"/python_dense_weight_answer.txt", 'w') as f:
    for data in total_weight_space:
        print(data, file=f)

-----------------------------------
input count_0
0.31738189360291846
-----weight-------
0.01641462
-----calc_result----
0.005209703178372338
------------8_final_answer---------
[0.0052097]
-----------------------------------
-----------------------------------
input count_1
0.0
-----weight-------
-0.00179761
-----calc_result----
-0.0
------------8_final_answer---------
[0.0052097]
-----------------------------------
-----------------------------------
input count_2
0.0
-----weight-------
-0.00110902
-----calc_result----
-0.0
------------8_final_answer---------
[0.0052097]
-----------------------------------
-----------------------------------
input count_3
0.26029098086194274
-----weight-------
-0.00925039
-----calc_result----
-0.002407793086455507
------------8_final_answer---------
[0.00280191]
-----------------------------------
-----------------------------------
input count_4
0.10873728125367926
-----weight-------
-0.00637908
-----calc_result----
-0.0006936438160997203
----------

In [33]:
dense_weight = read_parameter(file_serial="dense",file_name="weight",file_number=1)
dense_bias   = read_parameter(file_serial="dense",file_name="bias",file_number=1)
dense_weight = dense_weight.reshape(1,100,100)
dense_bias   = dense_bias.reshape(1,100)

weight file is open and read
bias file is open and read


In [67]:
Dense_float_result_sharp = Dense_float_result.reshape(1,100)
Dense_float_result_tmp = np.zeros((1,120))
Dense_float_result_tmp[:,:100] = Dense_float_result_sharp[:,:]
Dense_float_result_tmp = Dense_float_result_tmp.reshape(120)
tmp_weight = np.zeros((1,120,120))
tmp_weight[:,:100,:100] = dense_weight[:,:,:]
tmp_weight = tmp_weight.reshape(120,120)
tmp_bias = np.zeros((1,120))
tmp_bias[:,:100] = dense_bias[:,:]
answer = np.dot(Dense_float_result_tmp,tmp_weight) + tmp_bias
answer = nrelu(input_feature_map = answer, fixed_point = 0)
#print(answer)
data_array = read_hardware_output(Hex_file_location="./input_feature_map/SMART_Layer12.txt",shift_number=12,output_data_offset=5,total_eight_number=15)
data_array = data_array.reshape(120)
print(type(Dense_float_result_tmp))
print(Dense_float_result_tmp.shape)
print(type(data_array))
print(data_array.shape)
print("--------------------------")
#answer = np.dot(data_array,tmp_weight) + tmp_bias
#answer = nrelu(input_feature_map = answer, fixed_point = 0)
#print(answer)
#-------------------Dense for input reuse ------------------
x_total_round = int(120/24)
y_total_round = int(120/24)
PE_array = 8
three_bank = 3
two_four_weight = 24
total_test_space = np.zeros([1,120])
total_weight_space = np.zeros([120*120+240])
for y_side in range(y_total_round):
    for x_side in range(x_total_round):
        for bank in range(three_bank):
            for PE in range(PE_array):
                for count in range(two_four_weight):
                    x_jump_index = (bank*PE_array+PE) + x_side * 24
                    y_jump_index = y_side*24 + count
                    if(y_side!=y_total_round-1):
                        space_index = count + PE * two_four_weight * 3 + bank  * two_four_weight + x_side * 576 + y_side * x_total_round * 576
                    else:
                        space_index = count + PE * two_four_weight * 3 + bank  * two_four_weight + x_side * 576 + y_side * x_total_round * 576 + x_side * 48
                    #total_test_space[:,x_jump_index] = total_test_space[:,x_jump_index] + Dense_float_result_tmp[y_jump_index] * tmp_weight[y_jump_index][x_jump_index]
                    total_test_space[:,x_jump_index] = total_test_space[:,x_jump_index] + data_array[y_jump_index] * tmp_weight[y_jump_index][x_jump_index]
                    total_weight_space[space_index] = tmp_weight[y_jump_index][x_jump_index]
                    if(x_side==2 and y_side==0 and bank==2 and PE==7):
                        print("-----------------------------------")
                        print("input count_%d"%count)
                        #print(flatten_floating_answer_tmp[y_jump_index])
                        print(data_array[y_jump_index])
                        print("-----weight-------")
                        print(tmp_weight[y_jump_index][x_jump_index])
                        print("-----calc_result----")
                        #print(flatten_floating_answer_tmp[y_jump_index] * tmp_weight[y_jump_index][x_jump_index])
                        print(data_array[y_jump_index] * tmp_weight[y_jump_index][x_jump_index])
                        print("------------8_final_answer---------")
                        print(total_test_space[:,x_jump_index])
                        print("-----------------------------------")
                #print(total_test_space[:,x_jump_index])
    if(y_side==y_total_round-1):
        for alpha_index in range(two_four_weight):
            alpha_space_index = y_side * x_total_round * 576 + y_side * 48 + x_total_round * 576 + alpha_index
            total_weight_space[alpha_space_index] = 1
        for beta_index in range(two_four_weight):
            beta_space_index = y_side * x_total_round * 576 + y_side * 48 + x_total_round * 576 + 24 + beta_index
            total_weight_space[beta_space_index] = tmp_bias[:,x_side * two_four_weight + beta_index]
hw_answer = nrelu(input_feature_map = total_test_space + tmp_bias, fixed_point = 0)
print(hw_answer)
try:
    os.stat("./"+fix_point_dir+"/total_weight_space/")
except:
    os.mkdir("./"+fix_point_dir+"/total_weight_space/")
with open("./"+fix_point_dir+"/total_weight_space"+"/input_reuse_python_dense_weight_answer.txt", 'w') as f:
    for data in total_weight_space:
        print(data, file=f)

[[17186, 7512, 0, 0, 15448, 294, 479, 0], [0, 14771, 0, 9119, 14538, 0, 14463, 424], [0, 0, 12720, 15843, 139, 6710, 575, 15766], [11581, 0, 0, 12764, 0, 15420, 12099, 0], [17443, 97, 15772, 14517, 0, 0, 0, 0], [16105, 15982, 219, 2248, 6607, 16036, 6966, 0], [35, 0, 15937, 0, 8, 0, 7675, 0], [16314, 15619, 166, 0, 0, 19234, 0, 0], [14477, 12777, 1643, 15760, 0, 15331, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 13980, 0, 13026, 55, 0, 10029, 0], [13, 0, 0, 0, 0, 0, 13301, 0], [11727, 0, 0, 563, 17321, 0, 0, 14615], [0, 8347, 0, 0, 0, 17688, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]]
15
<class 'numpy.ndarray'>
(120,)
<class 'numpy.ndarray'>
(120,)
--------------------------
-----------------------------------
input count_0
4.19580078125
-----weight-------
-0.04996949
-----calc_result----
-0.20966202518066407
------------8_final_answer---------
[-0.20966203]
-----------------------------------
-----------------------------------
input count_1
1.833984375
-----weight-------
-0.11158162
-----calc_result--